name: annotation_crawler
version: 0.1.0
authors:
  - Matias Meno <m@tias.me>
  - Martin Flucka <martin.flucka@gmail.com>
  - Thomas Stephenson <ovangle@gmail.com>
description: Helps finding classes or methods with specific annotations.
homepage: https://github.com/exitlive/annotation_crawler
dev_dependencies:
  unittest: any
